### ISSUE TITLE
baramundi shim 15.4 20210811

### ISSUE THREAD

**Issue by baramundi-sfoerg** [rhboot/shim-review#198]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
[ baramundisoftware/shim-review@baramundi-shim-review_2021](https://github.com/baramundisoftware/shim-review/tree/baramundi-shim-20210811)
 - [x] completed README.md file with the necessary information
 https://github.com/baramundisoftware/shim-review/blob/baramundi-shim-20210811/README.md
 - [x] shim.efi to be signed
 https://github.com/baramundisoftware/shim-review/blob/baramundi-shim-20210811/shim_x64.efi
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 https://github.com/baramundisoftware/shim-review/blob/baramundi-shim-20210811/bsAG_EV_productive_2020.cer
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
 not used
 - [x] any extra patches to shim via your own git tree or as files
 No extra patches
 - [x] any extra patches to grub via your own git tree or as files
https://github.com/baramundisoftware/grub2
 - [x] build logs
  https://github.com/baramundisoftware/shim-review/blob/baramundi-shim-20210811/shim_x64_build.log
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries
https://github.com/baramundisoftware/shim-review/blob/baramundi-shim-20210811/Dockerfile

###### What organization or people are asking to have this signed:
baramundi software AG

###### What product or service is this for:
baramundi Management Suite

###### Please confirm this as the origin your shim.
Yes

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
The SHIM bootloader starts a grub2 which decides if it should boot the local installed windows operating system or netboot a windows PE image.
This is necessary to support remote operating system installation on clients in the LAN.
With a signed SHIM bootloader we are able to support clients with enabled secure boot feature.

###### How do you manage and protect the keys used in your SHIM?
Private key is stored in hardware module with controlled access.

###### Do you use EV certificates as embedded certificates in the SHIM?
Yes

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
vendor_db not used, no hashes allow-listed

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
No Linux kernel is used

###### fixed ?

Yes
The grub2 sources we use have it's origin in the commit https://git.launchpad.net/ubuntu/+source/grub2/tag/?h=applied/2.04-1ubuntu44

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim

shim:
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim

grub: 
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.04,https://www.gnu.org/software/grub/
grub.ubuntu,1,Ubuntu,grub2,2.04-1ubuntu44.2,https://www.ubuntu.com/
grub.baramundi,1,Baramundi,grub2,2.04-1ubuntu44.2-bblefi1,https://github.com/baramundisoftware/grub2

##### Were your old SHIM hashes provided to Microsoft ?
No. We changed the EV certificate embedded in the shim, so the old shim can only start grubs signed with the old ev certificate. 

##### grub2 bootloaders can not be verified ?
We used a new EV certificate which is only used for the new grub 2.04 which origin is the commit https://git.launchpad.net/ubuntu/+source/grub2/tag/?h=applied/2.04-1ubuntu44

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
Downstream RHEL/Fedora/Debian/Canonical like implementation
see: https://github.com/baramundisoftware/grub2

###### What is the origin and full version number of your bootloader (GRUB or other)?
grub 2.04 (extended) see: https://github.com/baramundisoftware/grub2
The grub2 sources we use have it's origin in the commit https://git.launchpad.net/ubuntu/+source/grub2/tag/?h=applied/2.04-1ubuntu44

###### If your SHIM launches any other components, please provide further details on what is launched
Our shim only launches the mentioned grub 2.04

###### please provide further details on what is launched and how it enforces Secureboot lockdown
The SHIM bootloader starts a grub2 which decides if it should boot the local installed windows operating system or netboot a windows PE image.
This is necessary to support remote operating system installation on clients in the LAN.
With a signed SHIM bootloader we are able to support clients with enabled secure boot feature.

###### apply. Please describe your strategy.
No certificate got reused. The EV certificate used for the shim is new. No need for vendor_dbx entry.

###### How do the launched components prevent execution of unauthenticated code?
with standard grub 2.04 functionality, we prevent to start any unsigned bootloader

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
We launch Windows and Windows PE loader and kernel

###### What changes were made since your SHIM was last signed?
no changes were made to the original shim

###### What is the SHA256 hash of your final SHIM binary?
shim_x64.efi SHA256 Hash:

397E6D03A862C6D269F6E27B93A2C39B0652F5FF203158FDDA7C8CB057AC1654

**Comment by frozencemetery** [comment]
Previous review was https://github.com/rhboot/shim-review/issues/130

**Comment by frozencemetery** [comment]
I'm unable to verify emails - PGP keys are not available.

**Comment by baramundi-sfoerg** [comment]
Hi again, 

you're right, I added the pgp key to the review-repository and updated the readme. 

Name: Simon Förg
Position: Software Developer
Email address: simon.foerg@baramundi.com
PGP key, signed by the other security contacts, and preferably also with signatures that are reasonably well known in the linux community: https://github.com/baramundisoftware/shim-review/blob/baramundi-shim-20210811/2483E061F86E7214_simon.foerg%40baramundi.com.asc 

Thanks a lot and best regards.

**Comment by frozencemetery** [comment]
Okay, I see key fingerprints, but only Felix's has been pushed to a keyserver.  Yours should be as well.

**Comment by baramundi-sfoerg** [comment]
Hi and sorry for keep you waiting.  
I pushed my public key to keyserver.pgp.com today. 
Hope, we did everything right for now and look forward to your review.

Best regards.

**Comment by frozencemetery** [comment]
Checking today, I see Felix's key, but still not Simon's.  Possibly keyserver.pgp.com doesn't sync, or maybe it choked on the umlaut - I'm not familiar with the service, and when I went to dig further, it required a captcha.

**Comment by baramundi-sfoerg** [comment]
Hmm, I see. Today I published my public key to https://pgp.mit.edu/ 
Hopefully this will work. I was able to find myself and Felix.

**Comment by frozencemetery** [comment]
I do see a key there, but that has a different fingerprint than what is specified in README.md.

**Comment by baramundi-sfoerg** [comment]
Great, glad to hear and thanks for the fast response. 
You're right, sorry, I forgot updating the rest of the links in this issue after branching and adding my key. Links should be correct now, I revised this issue. Thanks for your effort.

**Comment by ecos-platypus** [comment]
The contact information is not yet in the format that is expected and described in README.md. It is stated that for both security contacts, the PGP public key fingerprint should be listed README.md (missing for `simon.foerg@baramundi.com`). Furthermore, each security contact has to sign the public key of the other contact and push the signed public key to the keyservers.

**Comment by ecos-platypus** [comment]
Disclaimer: I am not an authorized reviewer but review other shims to reduce the workload of the authorized reviewers and speed up the process for everyone.

Review was conducted in accordance to the reviewer guidelines (https://github.com/rhboot/shim/wiki/reviewer-guidelines)

1. Vendor is new, PGP keys are okay now and can be reviewed by an authorized reviewer
2. Build is reproducible
3. Shim is built from upstream branch `15.4` (commit 16eeafe28c552bca36953d75581500887631a7f1)
4. All questions in issue template and README.md are answered
5. Embedded EV certificate stands in relation with the company (`businessCategory = Private Organization, serialNumber = HRB 2064, jurisdictionC = DE, jurisdictionST = Bayern, jurisdictionL = Augsburg, C = DE, ST = Bayern, L = Augsburg, street = Beim Glaspalast 1, O = baramundi software AG, CN = baramundi software AG`)
6. Private key is stored in hardware module
7. The embedded EV certificate has a duration of 3 years which is acceptable
8. The submitted shim binaries contain the sbat data listed in the issue
    1. The shim sbat entry is missing a vendor-specific line. The `baramundi` vendor extension used with GRUB is sensible
    2. GRUB is derived from Ubuntu and should hence include an intermediate ubuntu grub line (see the recent request #197 for an ubuntu shim)
9. GRUB is used as bootloader
10. Questions regarding GRUB
   1. GRUB 2.04 with Ubuntu patches
   2. No custom patches
11. No Linux Kernel is loaded
12. Not applicable, first shim application
13. Shim verifies GRUB, not sure about the verification of the loaded Windows binaries by GRUB

There are still some issues with sbat data. I also cannot verify how GRUB and Windows work together to ensure a secure boot chain, I leave that to another reviewer that has more experience with the Windows boot process.

**Comment by julian-klode** [comment]
Closing outdated request due to the recent round of CVEs in grub and shim requiring a new submission with fixes for all these CVEs.
